### ISSUE TITLE
In Paratext2 project adding a new test  does not assign the correct test id

### ISSUE THREAD

**Issue by sillsdev-dondillard** [sillsdev/dokimion#132]
**Describe the bug**
Before reorgainizing where the Mongo DB was ran, Paratext2 project did not have a test id of 1 assigned. We somehow got that project in that state and not sure how. It weas the only project with the issue. However, adding a new test case would always pick the correct next available id. Somwhere over 390 is expected today.

After reorganizing where the Mongo DB was ran, A test case added to Paratext2 last week assigned test case id 1 to the new test. That was OK because it was available. Today adding another new test resulted in test id 2 being overwritten. The next available test id is 392 and this should have bene assigned to today's new test.

**To Reproduce**
1. Login to Dokimion production
2. choose Paratext2 project
3. goto Test Cases
4. Click on the Plus sign (add new test
5. fill out values for all fields
6. click save

**Expected behavior**
A new test case shows in the right pane with a test case id of 392

**Actual behavior**
A new test case showed in the roght pane with a test case id of 2. Test id was already taken and thus was overwritten by the new test. It looks like the counter for next available id is not looking at the currently already used values.

**Comment by bobbeck55** [comment]
Sequencers collection in mongo database contains the maximum id for every collection. The collections on the production mongodb VM each should have an entry in this collection. Since they did not, I added them. The collections were copied from the former mongo database without utilizing the dokimion app so the sequencers collection was never updated.
