### ISSUE TITLE
Provide default mandatory attributes and values for any new project

### ISSUE THREAD

**Issue by sillsdev-dondillard** [sillsdev/dokimion#15]
1. Admin user only
Attribute tab ONLY available
Can add/delete attributes to a project(product). All attributes created by an admin are "default"
Can add/delete attribute values

2. Test Developer and Tester 

Attribute tab NOT available
All attributes for project (created by admin) are automatically applied when a test case is created. There are no non-default attributes
Can add/delete attribute values when test case is created

**Comment by bobbeck55** [comment]
The decision is made to hide the 'Add Attribute' button and ability to delete Attributes (the red circular minus) next to the attributes when they create Test cases.
As they are all mandatory.

Also on individual test cases 'Add attribute' is visible only to an admin.

**Comment by roopa0222** [comment]
Hide the 'Add Attribute' button and ability to delete Attributes (the red circular minus) next to the attributes when they Create Test cases .As they are all mandatory.

On the individual test cases 'Add attribute' is visible only to an admin.
