### ISSUE TITLE
Server - Create another user level between User and Admin

### ISSUE THREAD

**Issue by sillsdev-dondillard** [sillsdev/dokimion#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Admin - everything
Test Developer - Create a new test case until a test case is locked. Also all tester capabilities.
Tester - read only, execute tests, add results to a launch

**Describe alternatives you've considered**

**Additional context**

**Comment by bobbeck55** [comment]
Server side code implemented and unit tested. Invocation stubbed out in master branch.
