### ISSUE TITLE
Server - Provide ability for Admin to set a test case to readonly for all other user types

### ISSUE THREAD

**Issue by sillsdev-dondillard** [sillsdev/dokimion#19]
**Is your feature request related to a problem? Please describe.**
Sometimes one test case needs to be read-only for all user types
except administrator. Only an administrator should be able to "lock"
a test case.

**Describe the solution you'd like**
Add a button to the test case dialog. When clicked, this button will
"lock" the test case, preventing any updates until an admin unlocks
the test case.

**Comment by bobbeck55** [comment]
Working but stubbed out in server until front end portion is done.
