### ISSUE TITLE
Hide property field

### ISSUE THREAD

**Issue by sillsdev-dondillard** [sillsdev/dokimion#20]
**Is your feature request related to a problem? Please describe.**
Each test case has a property field with the add property button. We currently do not use the property field.

**Describe the solution you'd like**
For now hide the property field and any related buttons.

**Describe alternatives you've considered**
In the future we may want to use properties. So hiding it but keeping the code may be useful.

**Comment by sillsdev-dondillard** [comment]
@bobbeck55  I added details about what is desired for this enhancement.

**Comment by bobbeck55** [comment]
Sorry I meant issue #22
