### ISSUE TITLE
Provide Bulk Edit of test cases for Attributes

### ISSUE THREAD

**Issue by sillsdev-dondillard** [sillsdev/dokimion#21]
In the test case details window, let the user select multiple test cases. The right pane should display the test case for the 1st test case selected. When the user selects "add or delete attribute" for this test case, dokimion should perform the operation for all the selected test cases.

![image](https://github.com/sillsdev/dokimion/assets/107821526/2290e2c7-4ff8-4de4-83c0-b6fc428e1ac5)

**Comment by bobbeck55** [comment]
Our current approach is to have the front end send 1 or more messages to the back end when an attribute is added/deleted from mulitple test cases. Each message will contain the attribute update for a single test case. If this causes a performance problem, some significant back end work will be needed.
