### ISSUE TITLE
Provide ability to reduce left pane of a launch in order to have larger view of test steps (drag and drop?)

### ISSUE THREAD

**Issue by sillsdev-dondillard** [sillsdev/dokimion#22]
Provide ability to reduce left pane (tree side) of the launch details window in order to have larger view of launch and test steps. When changing the size of the left pane of the launch details window, the right side (test case side) should not change. Provide this functionality for the test case details window also.

**Comment by bobbeck55** [comment]
Done

**Comment by bobbeck55** [comment]
can left pane size be decreased while leaving the size of the right pane constant?
