### ISSUE TITLE
Get rid of attribute charts on launch screen. Numbers are wrong and charts are meaningless.

### ISSUE THREAD

**Issue by sillsdev-dondillard** [sillsdev/dokimion#23]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
Delete all graphs under the 2 restart buttons.

**Additional context**

**Comment by roopa0222** [comment]
![Launch_Attribute_Graphs](https://github.com/sillsdev/dokimion/assets/133702629/40d54117-57e5-4850-9fa4-dcfa5055c323)

**Comment by bobbeck55** [comment]
Attribute chart was deleted as part of another issue.
