### ISSUE TITLE
Calculate and Display Run Time for each Test Case in a Launch

### ISSUE THREAD

**Issue by sillsdev-dondillard** [sillsdev/dokimion#27]
The time duration for each test case in a launch should be displayed in a new column in the test case's history tab. This time is the difference between the time when the start button is clicked and the test results are saved. Also, the sum of the durations for each test case in a launch should be displayed in a new column in the launch overview window.

**Comment by roopa0222** [comment]
Code fixes are in staging on Dokimion4.
