### ISSUE TITLE
Test Case numbers in a launch are sorted as string values not integers

### ISSUE THREAD

**Issue by sillsdev-dondillard** [sillsdev/dokimion#28]
Problem: In the launch details window, test case numbers are sorted as strings.
Solution: Sort the test case numbers as integers. Also, check how the test case numbers are sorted in the test case details window.

**Comment by roopa0222** [comment]
Found some discrepancies on "Production" in case of TestSuite in the TestCase Numbers . Need to check

**Comment by roopa0222** [comment]
![Screenshot 2024-02-13 140739](https://github.com/sillsdev/dokimion/assets/133702629/21a0f99c-d9bb-4e4c-8ec9-09ff20602b51)
