### ISSUE TITLE
Statistics - Crashes without meaningful message

### ISSUE THREAD

**Issue by roopa0222** [sillsdev/dokimion#39]
**Describe the bug**
-When there are no launches created. When the user clicks on Statistics link on the Launch screen the app crashes instead of displaying an error or meaningful message

**To Reproduce**
.Steps to reproduce the behavior
1.Click on Launches in main header
2.Click on Statistics link
3. App crashes

**Expected behavior**
-It will be helpful to gracefully catch the error/exception behavior. It is a valid scenario as there are no statistics available since we do not have any launch data.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![Screenshot 2023-10-18 134829](https://github.com/sillsdev/dokimion/assets/133702629/82cfe3f3-ea29-42a8-b99c-5cad8a53f2c2)
![Screenshot 2023-10-18 135128](https://github.com/sillsdev/dokimion/assets/133702629/f62789ed-eed9-436b-a005-6c335fb1046e)

**Comment by bobbeck55** [comment]
Clicking on Statistics with no launches does not crash the dokimion app.
