### ISSUE TITLE
Launch creation error

### ISSUE THREAD

**Issue by bobbeck55** [sillsdev/dokimion#5]
**Describe the bug**
An attempt to create a launch from a rerun of an existing launch
results in a new launch created but also an error message.

**To Reproduce**
1. Click on existing launch "Launch12"
2. Click Restart failed
3. Name new launch "Launch12a"
4. Click Create and Close
5. Error message displayed - Couldn't get launch: TypeError: Cannot read properties of undefined (reading '0')

**Expected behavior**
No error message should appear.
New launch should be created without error

**Browser
Chrome

**Comment by sillsdev-dondillard** [comment]
Sometimes logout and login clears ondition. Sometimes closing Chrome and launching Chrome again clears condition

**Comment by roopa0222** [comment]
This is also verified in the automation process. 
We can get to the newly created Launch02 - Re-run from list of Launches and it displays properly.
![Screenshot 2023-10-18 131318](https://github.com/sillsdev/dokimion/assets/133702629/95e75b1a-5bfc-4410-bec3-03906d37810b)

**Comment by bobbeck55** [comment]
Cannot be reproduced. Closed unless or until it happens again.
