### ISSUE TITLE
Couldn't save Preconditions, Description, or Attributes in Test Case

### ISSUE THREAD

**Issue by bobbeck55** [sillsdev/dokimion#54]
When in the test case details window, an attempt to add or change an attribute, description, or preconditions field results in an error message - Couldn't save testcase...
Steps can be changed. This problem is in stage_testing.languagetechnology.org
BUT not in testing.languagetechnology.org. Here is a snippet.

![Screenshot 2023-12-18 152202](https://github.com/sillsdev/dokimion/assets/107821526/cdf374b4-9432-44c1-8031-f7034034bc7e)

**Comment by roopa0222** [comment]
Updated the code. Testcases are saved successfully with Description, Precondition and steps
