### ISSUE TITLE
Copy paste from Dokimion to Paratext not working sometimes

### ISSUE THREAD

**Issue by bobbeck55** [sillsdev/dokimion#55]
Problem:
When the user sets the style of some text to bold using the triple mouse click and then wants to select, copy, and paste some portion of the selected text to another application it does not work.

Solution: Allow copy and paste of a selected portion of a triple highlighted section of text.

**Comment by roopa0222** [comment]
Highlighting Text on select is default browser behavior. Not sure how to disable.
