### ISSUE TITLE
Add Attribute - success message when filter attribute set without value

### ISSUE THREAD

**Issue by bobbeck55** [sillsdev/dokimion#58]
In the test details window, a use puts an attribute in the field to the right of
the "Filter" label and a value in the next field to the right, the attribute specified
is added successfully.

However, if an attribute is added to the field to the right of the "Filter" label
BUT no value is added to the next field to the right, the normal "success" message
is displayed BUT no attribute is added to any of the selected test cases.
This scenario should generate an error message instead.

**Comment by roopa0222** [comment]
Modified the code to show error message
