### ISSUE TITLE
The Test case number is being overwritten or the Test case number sequence is not maintained in Dokimion API

### ISSUE THREAD

**Issue by roopa0222** [sillsdev/dokimion#83]
Need to investigate how the Test case number is maintained with the Dokimion API.

It is observed that the testcase numbers are over written when testcases are imported using tool. 

Instead of incrementing the testcase number existed in the database it overwrote. 
When the test cases are inserted into the Database using the tool (Mike provided).

Test Scenario
The new testcase that got inserted by the updater tool had the test case number as '1' instead of being added as a new test case with id (36) depending on the test cases in the database.

**Comment by bobbeck55** [comment]
Test case number is generated in the backend and cannot be set by the dokimion user.
