### ISSUE TITLE
The Role for 'Tester' in Production has a space. It should be 'TESTDEVELOPER'

### ISSUE THREAD

**Issue by roopa0222** [sillsdev/dokimion#99]
On Production in the database the role for Tester is stored as 'TEST DEVELOPER'. This could cause issue in the UI and in the code where we look for 'TESTDEVELOPER'. 

This needs to be corrected for Dokimion to grant proper access/privileges to users.

![Screenshot 2024-02-29 124522](https://github.com/sillsdev/dokimion/assets/133702629/310836ba-8944-42d6-ac5d-4c061cc736cb)

**Comment by bobbeck55** [comment]
The "Create User" command (admin accounts) should be updated to use "TESTDEVELOPER" instead of "TEST DEVELOPER".
